In [1]:
import json

import polars as pl

In [2]:
df = pl.read_parquet(
    '/Users/evrins/workspace/python/DNF_pvf_python/dnfpkgtool/repo/data/stackables.parquet'
)
df

shape: (14_493, 13)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ id       ┆ name      ┆ name2     ┆ json      ┆ … ┆ item_cate ┆ stack_lim ┆ stackable ┆ rarity_di │
│ ---      ┆ ---       ┆ ---       ┆ ---       ┆   ┆ gory      ┆ it        ┆ _type_dis ┆ splay     │
│ i64      ┆ str       ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ play      ┆ ---       │
│          ┆           ┆           ┆           ┆   ┆ str       ┆ i64       ┆ ---       ┆ str       │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ str       ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0        ┆ 金币      ┆ Gold      ┆ {"[name]" ┆ … ┆           ┆ 0         ┆ 消耗品    ┆ 高级      │
│          ┆           ┆           ┆ :         ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ ["金币"], ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ "[name2]" ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ : …       ┆   ┆           ┆           ┆           ┆           │
│ 1        ┆ 复活币    ┆ Coin      ┆ {"[name]" ┆ … ┆           ┆ 0         ┆ 其他      ┆ 普通      │
│          ┆           ┆           ┆ : ["复活  ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ 币"], "[n ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ ame2]":…  ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 决斗胜点  ┆ PvP       ┆ {"[name]" ┆ … ┆           ┆ 0         ┆ 其他      ┆ 普通      │
│          ┆           ┆ Victory   ┆ : ["决斗  ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆ Point     ┆ 胜点"],   ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ "[name2]" ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ …         ┆   ┆           ┆           ┆           ┆           │
│ 3        ┆ 遗忘河之  ┆ The River ┆ {"[name]" ┆ … ┆           ┆ 0         ┆ 其他      ┆ 神器      │
│          ┆ 水        ┆ of Lethe  ┆ : ["遗忘  ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ 河之水"], ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ "[name2]… ┆   ┆           ┆           ┆           ┆           │
│ 4        ┆ 普通金库  ┆ Basic     ┆ {"[name]" ┆ … ┆           ┆ 0         ┆ 其他      ┆ 高级      │
│          ┆           ┆ Store     ┆ : ["普通  ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ 金库"],   ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ "[name2]" ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ …         ┆   ┆           ┆           ┆           ┆           │
│ …        ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 20250927 ┆ 祖传武器  ┆           ┆ {"[name]" ┆ … ┆           ┆ 0         ┆ 礼包      ┆ 神器      │
│          ┆ 宝箱      ┆           ┆ : ["祖传  ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ 武器宝箱" ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ ],        ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ "[name2…  ┆   ┆           ┆           ┆           ┆           │
│ 83868    ┆ 有期限的  ┆           ┆ {"[name]" ┆ … ┆           ┆ 0         ┆ 礼包      ┆ 稀有      │
│          ┆ 稀有克隆  ┆           ┆ : ["有期  ┆   ┆           ┆           ┆           ┆           │
│          ┆ 装扮套装  ┆           ┆ 限的稀有  ┆   ┆           ┆           ┆           ┆           │
│          ┆ 礼盒      ┆           ┆ 克隆装扮  ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ 套装礼盒" ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ ],…       ┆   ┆           ┆           ┆           ┆           │
│ 2683028  ┆ Fate/Zero ┆           ┆ {"[name]" ┆ … ┆           ┆ 0         ┆ 礼包      ┆ 稀有      │
│          ┆ 诸王的命  ┆           ┆ : ["Fate/ ┆   ┆           ┆           ┆           ┆           │
│          ┆ 运装扮    ┆           ┆ Zero诸王  ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ 的命运装  ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ 扮"…      ┆   ┆           ┆           ┆           ┆           │
│ 8888     ┆ 命运的抉  ┆           ┆ {"[name]" ┆ … ┆           ┆ 1000      ┆ 其他      ┆ 神器      │
│          ┆ 择+15装备 ┆           ┆ : ["命运  ┆   ┆           ┆           ┆           ┆           │
│          ┆ 强化券    ┆           ┆ 的抉择+15 ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ 装备强化  ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ 券"], …   ┆   ┆           ┆           ┆           ┆           │
│ 2668888  ┆ 赛丽亚的  ┆ Shining   ┆ {"[name]" ┆ … ┆           ┆ 0         ┆ 消耗品    ┆ 神器      │
│          ┆ 援助      ┆ Hands of  ┆ : ["赛丽  ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆ Seria     ┆ 亚的援助" ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ ],        ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ "[name2…  ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [ ]:
df.filter(pl.col('stackable_type') == '[etc]').sort(pl.col('sub_stackable_type'))

In [ ]:
df.select(pl.col('stackable_type')).unique().sort(by=pl.col('stackable_type'))

In [ ]:
for it in df.select(pl.col('stackable_type')).to_series().unique().sort():
    print(f'df.filter(pl.col("stackable_type") == "{it}")')

In [ ]:
df.filter(pl.col('stackable_type') == '[avatar emblem]')

In [ ]:
df.filter(pl.col('stackable_type') == '[booster random]')

In [ ]:
df.filter(pl.col('stackable_type') == '[booster selection]')

In [ ]:
df.filter(pl.col('stackable_type') == '[booster]')

In [ ]:
df.filter(pl.col('stackable_type') == '[cera booster]')

In [ ]:
df.filter(pl.col('stackable_type') == '[cera package]')

In [ ]:
df.filter(pl.col('stackable_type') == '[contract]')

In [ ]:
df.filter(pl.col('stackable_type') == '[creature expitem]')

In [ ]:
df.filter(pl.col('stackable_type') == '[creature]')

In [ ]:
df.filter(pl.col('stackable_type') == '[disguise random]')

In [ ]:
df.filter(pl.col('stackable_type') == '[disguise]')

In [ ]:
df.filter(pl.col('stackable_type') == '[dye]')

In [ ]:
df.filter(pl.col('stackable_type') == '[enchant waste]')

In [ ]:
df.filter(pl.col('stackable_type') == '[etc]')

In [ ]:
df.filter(pl.col('stackable_type') == '[expert town potion]')

In [ ]:
df.filter(pl.col('stackable_type') == '[feed]')

In [ ]:
df.filter(pl.col('stackable_type') == '[global effect]')

In [ ]:
df.filter(pl.col('stackable_type') == '[legacy]')

In [ ]:
df.filter(pl.col('stackable_type') == '[material expert job]')

In [ ]:
df.filter(pl.col('stackable_type') == '[material]')

In [ ]:
df.filter(pl.col('stackable_type') == '[multi upgradable legacy bonus cera]')

In [ ]:
df.filter(pl.col('stackable_type') == '[multi upgradable legacy]')

In [ ]:
df.filter(pl.col('stackable_type') == '[only effect]')

In [ ]:
df.filter(pl.col('stackable_type') == '[quest]')

In [ ]:
df.filter(pl.col('stackable_type') == '[recipe]')

In [ ]:
df.filter(pl.col('stackable_type') == '[quest receive]')

In [ ]:
df.filter(pl.col('stackable_type') == '[set]')

In [ ]:
df.filter(pl.col('stackable_type') == '[stackable legacy]')

In [ ]:
df.filter(pl.col('stackable_type') == '[teleport potion]')

In [ ]:
df.filter(pl.col('stackable_type') == '[throw]')

In [ ]:
df.filter(pl.col('stackable_type') == '[town and dungeon]')

In [ ]:
df.filter(pl.col('stackable_type') == '[unlimited etc]')

In [ ]:
df.filter(pl.col('stackable_type') == '[unlimited town and dungeon]')

In [ ]:
df.filter(pl.col('stackable_type') == '[unlimited waste]')

In [ ]:
df.filter(pl.col('stackable_type') == '[upgradable legacy]')

In [ ]:
df.filter(pl.col('stackable_type') == '[upgrade limit cube]')

In [ ]:
df.filter(pl.col('stackable_type') == '[usable cera package]')

In [ ]:
df.filter(pl.col('stackable_type') == '[waste]')

In [ ]:
df.select(pl.col('item_category')).unique()

In [ ]:
# query card
df.filter(pl.col('item_category') == 'monster card')

In [ ]:
df.schema

In [ ]:
df.filter(pl.col('stackable_type_display') == '卡片')

In [ ]:
df.select(pl.col('rarity')).unique()

In [ ]:
df.filter(pl.col('item_category') == 'monster card')

In [ ]:
from collections import defaultdict
from typing import List

coll: dict[str, List[dict]] = defaultdict(list)
for it in (
    df.filter(pl.col('stackable_type') == '[enchant waste]').select('*').to_dicts()
):
    d = json.loads(it['json'])
    monster_card_id = d['[monster card id]']
    if not monster_card_id:
        print(f'monster card id not found in {it["id"]}')
    card = df.filter(pl.col('id') == monster_card_id[0]).to_dicts()[0]
    card_d = json.loads(card['json'])
    enchant_key = '[enchant]'
    if enchant_key not in card_d:
        print(f'enchant key {enchant_key} not found in card {card["name"]}')
        coll['others'].append(d)
        continue
    categories = card_d[enchant_key].keys()
    for c in categories:
        coll[c].append(d)

for k, v in coll.items():
    print(f'{k}')
    for d in v:
        print(f'\t{d}')

In [4]:
df.filter(pl.col('stack_limit') > 10)

shape: (2_213, 13)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id        ┆ name      ┆ name2     ┆ json      ┆ … ┆ item_cate ┆ stack_lim ┆ stackable ┆ rarity_d │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ gory      ┆ it        ┆ _type_dis ┆ isplay   │
│ i64       ┆ str       ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ play      ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ str       ┆ i64       ┆ ---       ┆ str      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ str       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2660674   ┆ 洗色剂    ┆           ┆ {"[name]" ┆ … ┆           ┆ 1000      ┆ 染色剂    ┆ 稀有     │
│           ┆           ┆           ┆ : ["洗色  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 剂"], "[n ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ame2]":…  ┆   ┆           ┆           ┆           ┆          │
│ 2660675   ┆ 珊瑚色染  ┆           ┆ {"[name]" ┆ … ┆           ┆ 1000      ┆ 染色剂    ┆ 稀有     │
│           ┆ 色剂      ┆           ┆ : ["珊瑚  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 色染色剂" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ],        ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name2…  ┆   ┆           ┆           ┆           ┆          │
│ 2660676   ┆ 杏黄色染  ┆           ┆ {"[name]" ┆ … ┆           ┆ 1000      ┆ 染色剂    ┆ 稀有     │
│           ┆ 色剂      ┆           ┆ : ["杏黄  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 色染色剂" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ],        ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name2…  ┆   ┆           ┆           ┆           ┆          │
│ 2660677   ┆ 土黄色染  ┆           ┆ {"[name]" ┆ … ┆           ┆ 1000      ┆ 染色剂    ┆ 稀有     │
│           ┆ 色剂      ┆           ┆ : ["土黄  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 色染色剂" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ],        ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name2…  ┆   ┆           ┆           ┆           ┆          │
│ 2660678   ┆ 绿色染色  ┆           ┆ {"[name]" ┆ … ┆           ┆ 1000      ┆ 染色剂    ┆ 稀有     │
│           ┆ 剂        ┆           ┆ : ["绿色  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 染色剂"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name2]… ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 690000852 ┆ 大师的契  ┆           ┆ {"[name]" ┆ … ┆           ┆ 1000      ┆ 礼包      ┆ 稀有     │
│           ┆ 约礼包(7  ┆           ┆ : ["大师  ┆   ┆           ┆           ┆           ┆          │
│           ┆ 天)       ┆           ┆ 的契约礼  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 包(7天)"] ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ , "[…     ┆   ┆           ┆           ┆           ┆          │
│ 690000853 ┆ 大师的契  ┆           ┆ {"[name]" ┆ … ┆           ┆ 1000      ┆ 礼包      ┆ 稀有     │
│           ┆ 约礼包(15 ┆           ┆ : ["大师  ┆   ┆           ┆           ┆           ┆          │
│           ┆ 天)       ┆           ┆ 的契约礼  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 包(15天)" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ], "…     ┆   ┆           ┆           ┆           ┆          │
│ 690001528 ┆ 魔奇少年  ┆           ┆ {"[name]" ┆ … ┆           ┆ 1000      ┆ 礼包      ┆ 神器     │
│           ┆ 宠物箱子  ┆           ┆ : ["魔奇  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 少年宠物  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 箱子"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[fla…    ┆   ┆           ┆           ┆           ┆          │
│ 202388980 ┆ 副本难度  ┆ Dungeon   ┆ {"[name]" ┆ … ┆           ┆ 1000      ┆ 其他      ┆ 稀有     │
│ 8         ┆ 解锁券    ┆ difficult ┆ : ["副本  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ y unlock  ┆ 难度解锁  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ tick…     ┆ 券"],     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name…   ┆   ┆           ┆           ┆           ┆          │
│ 8888      ┆ 命运的抉  ┆           ┆ {"[name]" ┆ … ┆           ┆ 1000      ┆ 其他      ┆ 神器     │
│           ┆ 择+15装备 ┆           ┆ : ["命运  ┆   ┆           ┆           ┆           ┆          │
│           ┆ 强化券    ┆           ┆ 的抉择+15 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 装备强化  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 券"], …   ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [5]:
df.filter(pl.col('id') == 10002515)

shape: (1, 13)
┌──────────┬────────────┬───────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ id       ┆ name       ┆ name2 ┆ json       ┆ … ┆ item_categ ┆ stack_limi ┆ stackable ┆ rarity_di │
│ ---      ┆ ---        ┆ ---   ┆ ---        ┆   ┆ ory        ┆ t          ┆ _type_dis ┆ splay     │
│ i64      ┆ str        ┆ str   ┆ str        ┆   ┆ ---        ┆ ---        ┆ play      ┆ ---       │
│          ┆            ┆       ┆            ┆   ┆ str        ┆ i64        ┆ ---       ┆ str       │
│          ┆            ┆       ┆            ┆   ┆            ┆            ┆ str       ┆           │
╞══════════╪════════════╪═══════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ 10002515 ┆ 念气矿石碎 ┆       ┆ {"[name]": ┆ … ┆            ┆ 1000       ┆ 材料      ┆ 稀有      │
│          ┆ 片         ┆       ┆ ["念气矿石 ┆   ┆            ┆            ┆           ┆           │
│          ┆            ┆       ┆ 碎片"],    ┆   ┆            ┆            ┆           ┆           │
│          ┆            ┆       ┆ "[expla…   ┆   ┆            ┆            ┆           ┆           │
└──────────┴────────────┴───────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘