In [40]:

import polars as pl

In [41]:
df = pl.read_parquet(
    '/Users/evrins/workspace/python/DNF_pvf_python/dnfpkgtool/repo/data/orbs.parquet'
)
df

shape: (261, 12)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ orb_id    ┆ orb_name  ┆ orb_name2 ┆ card_id   ┆ … ┆ enchant_c ┆ effect_di ┆ apply_par ┆ stat_des │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ategory_d ┆ splay     ┆ ts        ┆ c        │
│ i64       ┆ str       ┆ str       ┆ i64       ┆   ┆ isplay    ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ ---       ┆ str       ┆ list[str] ┆ str      │
│           ┆           ┆           ┆           ┆   ┆ list[str] ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2600294   ┆ 光之城主  ┆ Sieghart  ┆ 3600      ┆ … ┆ ["属性攻  ┆ 光        ┆ ["[weapon ┆          │
│           ┆ 赛格哈特  ┆ : Lord of ┆           ┆   ┆ 击"]      ┆           ┆ ]"]       ┆          │
│           ┆ 的宝珠    ┆ Light's   ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Cas…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2600295   ┆ 长脚罗特  ┆ Lotus of  ┆ 3601      ┆ … ┆ ["力量"]  ┆ +26       ┆ ["[weapon ┆          │
│           ┆ 斯的宝珠  ┆ Long Foot ┆           ┆   ┆           ┆           ┆ ]",       ┆          │
│           ┆           ┆ Bead      ┆           ┆   ┆           ┆           ┆ "[coat]", ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ "[pants…  ┆          │
│ 2600296   ┆ 邪龙斯皮  ┆ Head of   ┆ 3602      ┆ … ┆ ["魔法暴  ┆ +3%       ┆ ["[should ┆          │
│           ┆ 兹的宝珠  ┆ Spirrazzi ┆           ┆   ┆ 击率"]    ┆           ┆ er]"]     ┆          │
│           ┆           ┆ : Dead    ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Drago…    ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2600297   ┆ 魔笛使者  ┆ Peter The ┆ 3603      ┆ … ┆ ["智力"]  ┆ +26       ┆ ["[weapon ┆          │
│           ┆ 皮特的宝  ┆ Piper     ┆           ┆   ┆           ┆           ┆ ]",       ┆          │
│           ┆ 珠        ┆ Bead      ┆           ┆   ┆           ┆           ┆ "[coat]", ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ "[pants…  ┆          │
│ 2600298   ┆ 烈焰彼诺  ┆ Vinoshu   ┆ 3604      ┆ … ┆ ["属性攻  ┆ 火        ┆ ["[weapon ┆          │
│           ┆ 修的宝珠  ┆ of Flame  ┆           ┆   ┆ 击"]      ┆           ┆ ]"]       ┆          │
│           ┆           ┆ Bead      ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 690000298 ┆ 勇者的祝  ┆ summer    ┆ 690000299 ┆ … ┆ ["力量",  ┆ +20 +20   ┆ ["[weapon ┆          │
│           ┆ 福        ┆ bead      ┆           ┆   ┆ "智力"]   ┆           ┆ ]", "[wri ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ st]", …   ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ "[ri…     ┆          │
│ 10015655  ┆ 藏有女魔  ┆           ┆ 10015651  ┆ … ┆ ["技能等  ┆ 20-25 主  ┆ ["[should ┆          │
│           ┆ 法师佣兵  ┆           ┆           ┆   ┆ 级提升"]  ┆ 动技能等  ┆ er]", "[w ┆          │
│           ┆ 力量的宝  ┆           ┆           ┆   ┆           ┆ 级 +1     ┆ aist]",   ┆          │
│           ┆ 珠        ┆           ┆           ┆   ┆           ┆           ┆ "[sh…     ┆          │
│ 10015656  ┆ 藏有格斗  ┆           ┆ 10015652  ┆ … ┆ ["技能等  ┆ 30-35 主  ┆ ["[should ┆          │
│           ┆ 家佣兵力  ┆           ┆           ┆   ┆ 级提升"]  ┆ 动技能等  ┆ er]", "[w ┆          │
│           ┆ 量的宝珠  ┆           ┆           ┆   ┆           ┆ 级 +1     ┆ aist]",   ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ "[sh…     ┆          │
│ 10015657  ┆ 藏有女枪  ┆           ┆ 10015653  ┆ … ┆ ["技能等  ┆ 40-45 主  ┆ ["[should ┆          │
│           ┆ 手佣兵力  ┆           ┆           ┆   ┆ 级提升"]  ┆ 动技能等  ┆ er]", "[w ┆          │
│           ┆ 量的宝珠  ┆           ┆           ┆   ┆           ┆ 级 +1     ┆ aist]",   ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ "[sh…     ┆          │
│ 10015658  ┆ 藏有暗夜  ┆           ┆ 10015654  ┆ … ┆ ["技能等  ┆ 20-45 主  ┆ ["[should ┆          │
│           ┆ 使者佣兵  ┆           ┆           ┆   ┆ 级提升"]  ┆ 动技能等  ┆ er]", "[w ┆          │
│           ┆ 力量的宝  ┆           ┆           ┆   ┆           ┆ 级 +1     ┆ aist]",   ┆          │
│           ┆ 珠        ┆           ┆           ┆   ┆           ┆           ┆ "[sh…     ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [42]:
df.filter(pl.col('stat_desc') != '')

shape: (5, 12)
┌─────────┬────────────┬───────────┬─────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ orb_id  ┆ orb_name   ┆ orb_name2 ┆ card_id ┆ … ┆ enchant_ca ┆ effect_dis ┆ apply_par ┆ stat_desc │
│ ---     ┆ ---        ┆ ---       ┆ ---     ┆   ┆ tegory_dis ┆ play       ┆ ts        ┆ ---       │
│ i64     ┆ str        ┆ str       ┆ i64     ┆   ┆ play       ┆ ---        ┆ ---       ┆ str       │
│         ┆            ┆           ┆         ┆   ┆ ---        ┆ str        ┆ list[str] ┆           │
│         ┆            ┆           ┆         ┆   ┆ list[str]  ┆            ┆           ┆           │
╞═════════╪════════════╪═══════════╪═════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ 2600597 ┆ 饿鬼达鲁的 ┆           ┆ 3775    ┆ … ┆ ["特殊效果 ┆            ┆ ["[pants] ┆ 攻击时，  │
│         ┆ 宝珠       ┆           ┆         ┆   ┆ "]         ┆            ┆ "]        ┆ 有1%%的几 │
│         ┆            ┆           ┆         ┆   ┆            ┆            ┆           ┆ 率恢复200 │
│         ┆            ┆           ┆         ┆   ┆            ┆            ┆           ┆ 点HP。    │
│         ┆            ┆           ┆         ┆   ┆            ┆            ┆           ┆ (冷却时…  │
│ 2600600 ┆ 突击队长兰 ┆           ┆ 3778    ┆ … ┆ ["特殊效果 ┆            ┆ ["[suppor ┆ 攻击时，  │
│         ┆ 蒂卢斯的宝 ┆           ┆         ┆   ┆ "]         ┆            ┆ t]"]      ┆ 有1%%的几 │
│         ┆ 珠         ┆           ┆         ┆   ┆            ┆            ┆           ┆ 率使自身  │
│         ┆            ┆           ┆         ┆   ┆            ┆            ┆           ┆ 进入祝福  │
│         ┆            ┆           ┆         ┆   ┆            ┆            ┆           ┆ 状态，    │
│         ┆            ┆           ┆         ┆   ┆            ┆            ┆           ┆ 效果持…   │
│ 2600614 ┆ 魂 : 突击  ┆           ┆ 3792    ┆ … ┆ ["特殊效果 ┆            ┆ ["[suppor ┆ 攻击时，  │
│         ┆ 队长兰蒂卢 ┆           ┆         ┆   ┆ "]         ┆            ┆ t]"]      ┆ 有1%%的几 │
│         ┆ 斯的宝珠   ┆           ┆         ┆   ┆            ┆            ┆           ┆ 率使自身  │
│         ┆            ┆           ┆         ┆   ┆            ┆            ┆           ┆ 进入祝福  │
│         ┆            ┆           ┆         ┆   ┆            ┆            ┆           ┆ 状态，    │
│         ┆            ┆           ┆         ┆   ┆            ┆            ┆           ┆ 效果持…   │
│ 2600676 ┆ 雷鸣之帕米 ┆           ┆ 3797    ┆ … ┆ ["特殊效果 ┆            ┆ ["[pants] ┆ 被攻击时  │
│         ┆ 斯的宝珠   ┆           ┆         ┆   ┆ "]         ┆            ┆ "]        ┆ ， 有3%%  │
│         ┆            ┆           ┆         ┆   ┆            ┆            ┆           ┆ 的几率使  │
│         ┆            ┆           ┆         ┆   ┆            ┆            ┆           ┆ 自身进入  │
│         ┆            ┆           ┆         ┆   ┆            ┆            ┆           ┆ 伪装状态  │
│         ┆            ┆           ┆         ┆   ┆            ┆            ┆           ┆ ， 效果…  │
│ 2600678 ┆ 巨人波图拉 ┆           ┆ 3799    ┆ … ┆ ["特殊效果 ┆            ┆ ["[pants] ┆ 被攻击时  │
│         ┆ 的宝珠     ┆           ┆         ┆   ┆ "]         ┆            ┆ "]        ┆ ， 有3%%  │
│         ┆            ┆           ┆         ┆   ┆            ┆            ┆           ┆ 的几率使  │
│         ┆            ┆           ┆         ┆   ┆            ┆            ┆           ┆ 自身进入  │
│         ┆            ┆           ┆         ┆   ┆            ┆            ┆           ┆ 无敌状态  │
│         ┆            ┆           ┆         ┆   ┆            ┆            ┆           ┆ ， 效果…  │
└─────────┴────────────┴───────────┴─────────┴───┴────────────┴────────────┴───────────┴───────────┘

In [43]:
df.filter(pl.col('enchant_category').list.contains('[if]'))

shape: (0, 12)
┌────────┬──────────┬───────────┬─────────┬───┬─────────────┬─────────────┬────────────┬───────────┐
│ orb_id ┆ orb_name ┆ orb_name2 ┆ card_id ┆ … ┆ enchant_cat ┆ effect_disp ┆ apply_part ┆ stat_desc │
│ ---    ┆ ---      ┆ ---       ┆ ---     ┆   ┆ egory_displ ┆ lay         ┆ s          ┆ ---       │
│ i64    ┆ str      ┆ str       ┆ i64     ┆   ┆ ay          ┆ ---         ┆ ---        ┆ str       │
│        ┆          ┆           ┆         ┆   ┆ ---         ┆ str         ┆ list[str]  ┆           │
│        ┆          ┆           ┆         ┆   ┆ list[str]   ┆             ┆            ┆           │
╞════════╪══════════╪═══════════╪═════════╪═══╪═════════════╪═════════════╪════════════╪═══════════╡
└────────┴──────────┴───────────┴─────────┴───┴─────────────┴─────────────┴────────────┴───────────┘

In [44]:
category_list = df.select(pl.col('enchant_category')).to_series().to_list()
category_list

[['[elemental property]'],
 ['[physical attack]'],
 ['[magical critical hit]'],
 ['[magical attack]'],
 ['[elemental property]'],
 ['[all elemental resistance]'],
 ['[HP MAX]'],
 ['[HP regen speed]'],
 ['[attack speed]'],
 ['[move speed]'],
 ['[cast speed]'],
 ['[HP MAX]'],
 ['[stone resistance]'],
 ['[dark resistance]'],
 ['[MP MAX]'],
 ['[fire resistance]'],
 ['[MP regen speed]'],
 ['[stuck resistance]'],
 ['[physical critical hit]'],
 ['[stuck resistance]'],
 ['[jump power]'],
 ['[HP MAX]'],
 ['[light resistance]'],
 ['[cast speed]'],
 ['[attack speed]'],
 ['[physical attack]'],
 ['[magical attack]'],
 ['[hold resistance]'],
 ['[slow resistance]'],
 ['[stuck]'],
 ['[move speed]'],
 ['[light attack]'],
 ['[physical attack]'],
 ['[magical attack]'],
 ['[water attack]'],
 ['[dark attack]'],
 ['[fire attack]'],
 ['[equipment physical attack]'],
 ['[HP MAX]'],
 ['[magical defense]'],
 ['[physical defense]'],
 ['[equipment magical attack]'],
 ['[rigidity]'],
 ['[MP MAX]'],
 ['[light attack]'],
 ['[water attack]'],
 ['[MP MAX]'],
 ['[rigidity]'],
 ['[magical defense]'],
 ['[equipment magical attack]'],
 ['[magical attack]'],
 ['[fire attack]'],
 ['[physical defense]'],
 ['[dark attack]'],
 ['[physical attack]'],
 ['[equipment physical attack]'],
 ['[HP MAX]'],
 ['[water attack]'],
 ['[MP MAX]'],
 ['[physical defense]'],
 ['[physical attack]'],
 ['[HP MAX]'],
 ['[magical defense]'],
 ['[dark attack]'],
 ['[fire attack]'],
 ['[equipment magical attack]'],
 ['[rigidity]'],
 ['[light attack]'],
 ['[equipment physical attack]'],
 ['[magical attack]'],
 ['[magical defense]'],
 ['[MP MAX]'],
 ['[fire attack]'],
 ['[rigidity]'],
 ['[equipment physical attack]'],
 ['[dark attack]'],
 ['[water attack]'],
 ['[magical attack]'],
 ['[physical defense]'],
 ['[HP MAX]'],
 ['[light attack]'],
 ['[equipment magical attack]'],
 ['[physical attack]'],
 ['[skill levelup]', ''],
 ['[skill levelup]', ''],
 ['[skill levelup]', ''],
 ['[skill levelup]', ''],
 ['[skill levelup]', ''],
 ['[skill levelup]', ''],
 ['[skill levelup]', ''],
 ['[rigidity]', '[hit recovery]'],
 ['[physical defense]', '[magical defense]'],
 ['[HP MAX]', '[MP MAX]'],
 ['[equipment physical attack]', '[equipment magical attack]'],
 ['[physical attack]', '[magical attack]'],
 ['[rigidity]'],
 ['[physical defense]'],
 ['[dark attack]'],
 ['[magical defense]'],
 ['[MP MAX]'],
 ['[HP MAX]'],
 ['[physical attack]'],
 ['[magical attack]'],
 ['[equipment magical attack]'],
 ['[fire attack]'],
 ['[equipment physical attack]'],
 ['[water attack]'],
 ['[attack speed]', '[cast speed]'],
 ['[attack speed]', '[cast speed]'],
 ['[attack speed]', '[cast speed]'],
 ['[physical attack]', '[magical attack]'],
 ['[physical attack]', '[magical attack]'],
 ['[physical attack]', '[magical attack]'],
 ['[attack speed]'],
 ['[magical critical hit]'],
 ['[elemental property]'],
 ['[dark attack]'],
 ['[cast speed]'],
 ['[equipment magical attack]'],
 ['[equipment physical attack]'],
 ['[skill levelup]', '[equipment physical attack]'],
 ['[skill levelup]', '[equipment magical attack]'],
 ['[skill levelup]', '[cast speed]'],
 ['[physical attack]', '[magical attack]'],
 ['[separate attack]'],
 ['[separate attack]'],
 ['[separate attack]'],
 ['[separate attack]'],
 ['[dark attack]'],
 ['[magical attack]'],
 ['[light attack]'],
 ['[fire attack]', '[light attack]', '[water attack]', '[dark attack]'],
 ['[fire attack]', '[light attack]', '[water attack]', '[dark attack]'],
 ['[physical attack]', '[magical attack]'],
 ['[physical attack]', '[magical attack]'],
 ['[all elemental attack]'],
 ['[all elemental attack]'],
 ['[all elemental attack]'],
 ['[poison resistance]'],
 ['[all elemental resistance]'],
 ['[HP regen speed]'],
 ['[rigidity]'],
 ['[magical defense]'],
 ['[stuck]'],
 ['[physical defense]'],
 ['[magical attack]'],
 ['[attack speed]'],
 ['[physical attack]'],
 ['[equipment physical attack]'],
 ['[equipment magical attack]'],
 ['[separate attack]'],
 ['[physical critical hit]'],
 ['[magical critical hit]'],
 ['[all elemental attack]'],
 ['[MP MAX]'],
 ['[equipment physical attack]'],
 ['[equipment magical attack]'],
 ['[dark attack]', '[separate attack]'],
 ['[jump power]'],
 ['[HP MAX]'],
 ['[stuck]'],
 ['[separate attack]'],
 ['[MP regen speed]'],
 ['[physical defense]'],
 ['[all activestatus resistance]'],
 ['[physical critical hit]'],
 ['[attack speed]'],
 ['[elemental property]'],
 ['special'],
 ['[magical critical hit]'],
 ['[magical attack]'],
 ['special'],
 ['[stuck resistance]'],
 ['[MP MAX]'],
 ['[physical defense]', '[magical defense]'],
 ['[fire attack]'],
 ['[MP regen speed]'],
 ['[equipment physical attack]'],
 ['[physical defense]'],
 ['[magical attack]', '[equipment magical attack]'],
 ['[stuck]'],
 ['[equipment physical attack]', '[equipment magical attack]'],
 ['[magical attack]'],
 ['[elemental property]', '[equipment physical attack]'],
 ['[physical critical hit]'],
 ['special'],
 ['[physical attack]', '[move speed]'],
 ['[magical attack]', '[move speed]'],
 ['[fire resistance]'],
 ['[physical critical hit]', '[magical critical hit]'],
 ['[hit recovery]'],
 ['[HP MAX]', '[MP MAX]'],
 ['[attack speed]', '[cast speed]'],
 ['[fire resistance]'],
 ['[separate attack]', '[fire attack]'],
 ['[stuck resistance]'],
 ['[physical attack]', '[magical attack]'],
 ['special'],
 ['[attack speed]'],
 ['special'],
 ['[physical critical hit]', '[magical critical hit]'],
 ['[equipment physical attack]'],
 ['[equipment physical attack]', '[separate attack]'],
 ['[equipment magical attack]'],
 ['[equipment magical attack]', '[separate attack]'],
 ['[separate attack]'],
 ['[separate attack]'],
 ['[equipment magical attack]'],
 ['[equipment physical attack]'],
 ['[separate attack]'],
 ['[equipment magical attack]'],
 ['[equipment physical attack]'],
 ['[dark attack]'],
 ['[dark attack]'],
 ['[dark attack]'],
 ['[dark attack]'],
 ['[fire attack]'],
 ['[fire attack]'],
 ['[fire attack]'],
 ['[fire attack]'],
 ['[light attack]'],
 ['[light attack]'],
 ['[light attack]'],
 ['[light attack]'],
 ['[water attack]'],
 ['[water attack]'],
 ['[water attack]'],
 ['[water attack]'],
 ['[dark attack]'],
 ['[fire attack]'],
 ['[light attack]'],
 ['[water attack]'],
 ['[equipment physical attack]',
  '[equipment magical attack]',
  '[separate attack]'],
 ['[equipment physical attack]'],
 ['[equipment magical attack]'],
 ['[separate attack]'],
 ['[equipment physical attack]', '[physical critical hit]'],
 ['[equipment magical attack]', '[magical critical hit]'],
 ['[separate attack]', '[physical critical hit]', '[magical critical hit]'],
 ['[fire attack]', '[dark attack]'],
 ['[all elemental attack]'],
 ['[light attack]', '[water attack]'],
 ['[equipment physical attack]'],
 ['[equipment magical attack]'],
 ['[separate attack]'],
 ['[physical attack]',
  '[magical attack]',
  '[physical defense]',
  '[magical defense]',
  '[physical critical hit]',
  '[all skill item container]',
  '[magical critical hit]'],
 ['[all elemental attack]',
  '[equipment physical attack]',
  '[equipment magical attack]',
  '[all skill item container]',
  '[separate attack]'],
 ['[equipment physical attack]',
  '[equipment magical attack]',
  '[separate attack]'],
 ['[all elemental attack]'],
 ['[equipment physical attack]',
  '[equipment magical attack]',
  '[separate attack]'],
 ['[equipment physical attack]',
  '[equipment magical attack]',
  '[separate attack]'],
 ['[equipment physical attack]',
  '[equipment magical attack]',
  '[all skill item container]',
  '[separate attack]'],
 ['[equipment physical attack]',
  '[equipment magical attack]',
  '[separate attack]',
  '[/enchant index]'],
 ['[equipment physical attack]',
  '[equipment magical attack]',
  '[all skill item container]',
  '[separate attack]'],
 ['[all elemental attack]',
  '[equipment physical attack]',
  '[equipment magical attack]',
  '[all skill item container]',
  '[separate attack]'],
 ['[physical attack]',
  '[magical attack]',
  '[physical defense]',
  '[magical defense]',
  '[physical critical hit]',
  '[all skill item container]',
  '[magical critical hit]'],
 ['[physical attack]', '[magical attack]'],
 ['[all skill item]', ''],
 ['[all skill item]', ''],
 ['[all skill item]', ''],
 ['[all skill item]', '']]

In [45]:
from itertools import chain

category_set = set(chain.from_iterable(category_list))
print(len(category_set))

for c in category_set:
    print(f"'{c}': '',")

42
'': '',
'[HP MAX]': '',
'[all activestatus resistance]': '',
'[attack speed]': '',
'[stuck]': '',
'[jump power]': '',
'[equipment physical attack]': '',
'[stone resistance]': '',
'[all elemental resistance]': '',
'[dark attack]': '',
'[equipment magical attack]': '',
'[stuck resistance]': '',
'[HP regen speed]': '',
'[poison resistance]': '',
'[move speed]': '',
'[magical attack]': '',
'[/enchant index]': '',
'[magical critical hit]': '',
'[skill levelup]': '',
'[separate attack]': '',
'[fire resistance]': '',
'[elemental property]': '',
'[light attack]': '',
'special': '',
'[light resistance]': '',
'[MP regen speed]': '',
'[physical attack]': '',
'[cast speed]': '',
'[physical critical hit]': '',
'[MP MAX]': '',
'[all skill item]': '',
'[slow resistance]': '',
'[hit recovery]': '',
'[hold resistance]': '',
'[physical defense]': '',
'[rigidity]': '',
'[all skill item container]': '',
'[fire attack]': '',
'[magical defense]': '',
'[water attack]': '',
'[all elemental attack]': '',
'[dark resistance]': '',

In [46]:
from itertools import chain

category_list = df.select(pl.col('enchant_category_display')).to_series().to_list()
category_set = set(chain.from_iterable(category_list))
print(len(category_set))

for c in category_set:
    print(f"'{c}': '',")

38
'物理防御': '',
'光属性强化': '',
'HP 回复速度': '',
'特殊效果': '',
'智力': '',
'暗属性抗性': '',
'中毒抗性': '',
'减速抗性': '',
'火属性强化': '',
'暗属性强化': '',
'释放速度': '',
'硬直': '',
'冰属性强化': '',
'所有异常状态抗性': '',
'独立攻击力': '',
'所有属性抗性': '',
'光属性抗性': '',
'火属性抗性': '',
'跳跃力': '',
'物理攻击力': '',
'攻击速度': '',
'HP 最大值': '',
'魔法暴击率': '',
'魔法攻击力': '',
'力量': '',
'命中率': '',
'回避率': '',
'魔法防御': '',
'所有属性强化': '',
'属性攻击': '',
'MP 最大值': '',
'石化抗性': '',
'束缚抗性': '',
'MP 回复速度': '',
'僵直': '',
'物理暴击率': '',
'移动速度': '',
'技能等级提升': '',

In [47]:
df.filter(pl.col('enchant_category_display').list.contains('光属性强化'
                                                           ''))

shape: (13, 12)
┌──────────┬────────────┬───────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ orb_id   ┆ orb_name   ┆ orb_name2 ┆ card_id  ┆ … ┆ enchant_c ┆ effect_di ┆ apply_par ┆ stat_desc │
│ ---      ┆ ---        ┆ ---       ┆ ---      ┆   ┆ ategory_d ┆ splay     ┆ ts        ┆ ---       │
│ i64      ┆ str        ┆ str       ┆ i64      ┆   ┆ isplay    ┆ ---       ┆ ---       ┆ str       │
│          ┆            ┆           ┆          ┆   ┆ ---       ┆ str       ┆ list[str] ┆           │
│          ┆            ┆           ┆          ┆   ┆ list[str] ┆           ┆           ┆           │
╞══════════╪════════════╪═══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2600325  ┆ EX多尼尔的 ┆ Dornier   ┆ 3638     ┆ … ┆ ["光属性  ┆ +3        ┆ ["[amulet ┆           │
│          ┆ 宝珠       ┆ EX  Bead  ┆          ┆   ┆ 强化"]    ┆           ┆ ]", "[wri ┆           │
│          ┆            ┆           ┆          ┆   ┆           ┆           ┆ st]",     ┆           │
│          ┆            ┆           ┆          ┆   ┆           ┆           ┆ "[ring…   ┆           │
│ 2600338  ┆ 艾克洛索的 ┆ Aracloso  ┆ 3651     ┆ … ┆ ["光属性  ┆ +6        ┆ ["[amulet ┆           │
│          ┆ 宝珠       ┆ Bead      ┆          ┆   ┆ 强化"]    ┆           ┆ ]", "[wri ┆           │
│          ┆            ┆           ┆          ┆   ┆           ┆           ┆ st]",     ┆           │
│          ┆            ┆           ┆          ┆   ┆           ┆           ┆ "[ring…   ┆           │
│ 2600361  ┆ 莫格尼斯的 ┆ Magneus   ┆ 3674     ┆ … ┆ ["光属性  ┆ +9        ┆ ["[amulet ┆           │
│          ┆ 宝珠       ┆ Bead      ┆          ┆   ┆ 强化"]    ┆           ┆ ]", "[wri ┆           │
│          ┆            ┆           ┆          ┆   ┆           ┆           ┆ st]",     ┆           │
│          ┆            ┆           ┆          ┆   ┆           ┆           ┆ "[ring…   ┆           │
│ 2600374  ┆ 贝奡笔J的  ┆ Basilisk  ┆ 3687     ┆ … ┆ ["光属性  ┆ +12       ┆ ["[amulet ┆           │
│          ┆ 宝珠       ┆ Bead      ┆          ┆   ┆ 强化"]    ┆           ┆ ]", "[wri ┆           │
│          ┆            ┆           ┆          ┆   ┆           ┆           ┆ st]",     ┆           │
│          ┆            ┆           ┆          ┆   ┆           ┆           ┆ "[ring…   ┆           │
│ 2600450  ┆ 圣者米歇尔 ┆ The holy  ┆ 3737     ┆ … ┆ ["光属性  ┆ +11       ┆ ["[amulet ┆           │
│          ┆ 的宝珠     ┆ eyes,     ┆          ┆   ┆ 强化"]    ┆           ┆ ]", "[wri ┆           │
│          ┆            ┆ Michaela  ┆          ┆   ┆           ┆           ┆ st]",     ┆           │
│          ┆            ┆ Bead      ┆          ┆   ┆           ┆           ┆ "[ring…   ┆           │
│ …        ┆ …          ┆ …         ┆ …        ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 10000562 ┆ 光属性强化 ┆           ┆ 3810     ┆ … ┆ ["光属性  ┆ +6        ┆ ["[amulet ┆           │
│          ┆ +6卷轴[佩  ┆           ┆          ┆   ┆ 强化"]    ┆           ┆ ]", "[wri ┆           │
│          ┆ 伦魂]      ┆           ┆          ┆   ┆           ┆           ┆ st]",     ┆           │
│          ┆            ┆           ┆          ┆   ┆           ┆           ┆ "[ring…   ┆           │
│ 10000563 ┆ 光属性强化 ┆           ┆ 3811     ┆ … ┆ ["光属性  ┆ +9        ┆ ["[amulet ┆           │
│          ┆ +9卷轴[佩  ┆           ┆          ┆   ┆ 强化"]    ┆           ┆ ]", "[wri ┆           │
│          ┆ 伦魂]      ┆           ┆          ┆   ┆           ┆           ┆ st]",     ┆           │
│          ┆            ┆           ┆          ┆   ┆           ┆           ┆ "[ring…   ┆           │
│ 10000564 ┆ 光属性强化 ┆           ┆ 3812     ┆ … ┆ ["光属性  ┆ +12       ┆ ["[amulet ┆           │
│          ┆ +12卷轴[佩 ┆           ┆          ┆   ┆ 强化"]    ┆           ┆ ]", "[wri ┆           │
│          ┆ 伦魂]      ┆           ┆          ┆   ┆           ┆           ┆ st]",     ┆           │
│          ┆            ┆           ┆          ┆   ┆           ┆           ┆ "[ring…   ┆           │
│ 10000600 ┆ 光属性强化 ┆           ┆ 3819     ┆ … ┆ ["光属性  ┆ +13       ┆ ["[amulet ┆           │
│          ┆ +13卷轴[佩 ┆           ┆          ┆   ┆ 强化"]    ┆           ┆ ]", "[wri ┆           │
│          ┆ 伦魂]      ┆           ┆          ┆   ┆           ┆           ┆ st]",     ┆           │
│          ┆            ┆           ┆          ┆   ┆           ┆           ┆ "[ring…   ┆           │
│ 10007556 ┆ 生肖之灵宝 ┆           ┆ 10007568 ┆ … ┆ ["光属性  ┆ +10 +10   ┆ ["[amulet ┆           │
│          ┆ 珠 - 猴    ┆           ┆          ┆   ┆ 强化",    ┆           ┆ ]", "[wri ┆           │
│          ┆            ┆           ┆          ┆   ┆ "冰属性强 ┆           ┆ st]",     ┆           │
│          ┆            ┆           ┆          ┆   ┆ 化"]      ┆           ┆ "[ring…   ┆           │
└──────────┴────────────┴───────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [48]:
df.filter(pl.col('enchant_category_display').list.contains('属性攻击'))

shape: (5, 12)
┌─────────┬────────────┬────────────┬─────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ orb_id  ┆ orb_name   ┆ orb_name2  ┆ card_id ┆ … ┆ enchant_ca ┆ effect_di ┆ apply_par ┆ stat_desc │
│ ---     ┆ ---        ┆ ---        ┆ ---     ┆   ┆ tegory_dis ┆ splay     ┆ ts        ┆ ---       │
│ i64     ┆ str        ┆ str        ┆ i64     ┆   ┆ play       ┆ ---       ┆ ---       ┆ str       │
│         ┆            ┆            ┆         ┆   ┆ ---        ┆ str       ┆ list[str] ┆           │
│         ┆            ┆            ┆         ┆   ┆ list[str]  ┆           ┆           ┆           │
╞═════════╪════════════╪════════════╪═════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 2600294 ┆ 光之城主赛 ┆ Sieghart : ┆ 3600    ┆ … ┆ ["属性攻击 ┆ 光        ┆ ["[weapon ┆           │
│         ┆ 格哈特的宝 ┆ Lord of    ┆         ┆   ┆ "]         ┆           ┆ ]"]       ┆           │
│         ┆ 珠         ┆ Light's    ┆         ┆   ┆            ┆           ┆           ┆           │
│         ┆            ┆ Cas…       ┆         ┆   ┆            ┆           ┆           ┆           │
│ 2600298 ┆ 烈焰彼诺修 ┆ Vinoshu of ┆ 3604    ┆ … ┆ ["属性攻击 ┆ 火        ┆ ["[weapon ┆           │
│         ┆ 的宝珠     ┆ Flame Bead ┆         ┆   ┆ "]         ┆           ┆ ]"]       ┆           │
│ 2600422 ┆ 黑色瘟疫狄 ┆ The wicked ┆ 3722    ┆ … ┆ ["属性攻击 ┆ 暗        ┆ ["[weapon ┆           │
│         ┆ 瑞吉的宝珠 ┆ disease    ┆         ┆   ┆ "]         ┆           ┆ ]"]       ┆           │
│         ┆            ┆ Direzie    ┆         ┆   ┆            ┆           ┆           ┆           │
│         ┆            ┆ Bea…       ┆         ┆   ┆            ┆           ┆           ┆           │
│ 2600596 ┆ 年轻时的斯 ┆            ┆ 3774    ┆ … ┆ ["属性攻击 ┆ 冰        ┆ ["[weapon ┆           │
│         ┆ 卡萨的宝珠 ┆            ┆         ┆   ┆ "]         ┆           ┆ ]"]       ┆           │
│ 2600612 ┆ 魂 : 黑色  ┆            ┆ 3790    ┆ … ┆ ["属性攻击 ┆ 暗 +20    ┆ ["[weapon ┆           │
│         ┆ 瘟疫狄瑞吉 ┆            ┆         ┆   ┆ ", "物理攻 ┆           ┆ ]"]       ┆           │
│         ┆ 的宝珠     ┆            ┆         ┆   ┆ 击力"]     ┆           ┆           ┆           │
└─────────┴────────────┴────────────┴─────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [49]:
df.filter(pl.col('enchant_category_display').list.contains('技能等级提升'))

shape: (20, 12)
┌──────────┬────────────┬───────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ orb_id   ┆ orb_name   ┆ orb_name2 ┆ card_id  ┆ … ┆ enchant_c ┆ effect_di ┆ apply_par ┆ stat_desc │
│ ---      ┆ ---        ┆ ---       ┆ ---      ┆   ┆ ategory_d ┆ splay     ┆ ts        ┆ ---       │
│ i64      ┆ str        ┆ str       ┆ i64      ┆   ┆ isplay    ┆ ---       ┆ ---       ┆ str       │
│          ┆            ┆           ┆          ┆   ┆ ---       ┆ str       ┆ list[str] ┆           │
│          ┆            ┆           ┆          ┆   ┆ list[str] ┆           ┆           ┆           │
╞══════════╪════════════╪═══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2600377  ┆ 炎猫妖的宝 ┆ Akaru     ┆ 3690     ┆ … ┆ ["技能等  ┆ 三段斩 +1 ┆ ["[waist] ┆           │
│          ┆ 珠         ┆ Bead      ┆          ┆   ┆ 级提升"]  ┆ 金刚碎 +1 ┆ "]        ┆           │
│          ┆            ┆           ┆          ┆   ┆           ┆ 金刚碎 +1 ┆           ┆           │
│          ┆            ┆           ┆          ┆   ┆           ┆ 瞬踢 +1   ┆           ┆           │
│          ┆            ┆           ┆          ┆   ┆           ┆ 刺踢 …    ┆           ┆           │
│ 2600378  ┆ 灵幻师的宝 ┆ Phantasm  ┆ 3691     ┆ … ┆ ["技能等  ┆ 地裂 ·    ┆ ["[should ┆           │
│          ┆ 珠         ┆ Manipulat ┆          ┆   ┆ 级提升"]  ┆ 波动剑 +1 ┆ er]"]     ┆           │
│          ┆            ┆ or Bead   ┆          ┆   ┆           ┆ 念气波 +1 ┆           ┆           │
│          ┆            ┆           ┆          ┆   ┆           ┆ 念气波 +1 ┆           ┆           │
│          ┆            ┆           ┆          ┆   ┆           ┆ RX-7…     ┆           ┆           │
│ 2600379  ┆ 驯兽者伽罗 ┆ Tamer     ┆ 3692     ┆ … ┆ ["技能等  ┆ 生命源泉  ┆ ["[amulet ┆           │
│          ┆ 华的宝珠   ┆ Galois    ┆          ┆   ┆ 级提升"]  ┆ +1 神圣组 ┆ ]"]       ┆           │
│          ┆            ┆ Bead      ┆          ┆   ┆           ┆ 合拳 +1   ┆           ┆           │
│          ┆            ┆           ┆          ┆   ┆           ┆ 疾空旋风  ┆           ┆           │
│          ┆            ┆           ┆          ┆   ┆           ┆ 破 +1     ┆           ┆           │
│ 2600380  ┆ 尚武者伦茨 ┆ Lenz, The ┆ 3693     ┆ … ┆ ["技能等  ┆ 乱射 +1   ┆ ["[amulet ┆           │
│          ┆ 的宝珠     ┆ master of ┆          ┆   ┆ 级提升"]  ┆ 枪舞 +1   ┆ ]"]       ┆           │
│          ┆            ┆ martial   ┆          ┆   ┆           ┆ 量子爆弹  ┆           ┆           │
│          ┆            ┆ ar…       ┆          ┆   ┆           ┆ +1        ┆           ┆           │
│          ┆            ┆           ┆          ┆   ┆           ┆ 量子爆弹  ┆           ┆           │
│          ┆            ┆           ┆          ┆   ┆           ┆ +1 空投…  ┆           ┆           │
│ 2600381  ┆ 魔法变异者 ┆ Magical   ┆ 3694     ┆ … ┆ ["技能等  ┆ 天雷 +1   ┆ ["[amulet ┆           │
│          ┆ 霍伊恩的宝 ┆ mutant    ┆          ┆   ┆ 级提升"]  ┆ 精灵召唤  ┆ ]"]       ┆           │
│          ┆ 珠         ┆ Hwaian    ┆          ┆   ┆           ┆ :         ┆           ┆           │
│          ┆            ┆ Bead      ┆          ┆   ┆           ┆ 伊伽贝拉  ┆           ┆           │
│          ┆            ┆           ┆          ┆   ┆           ┆ +1 强袭流 ┆           ┆           │
│          ┆            ┆           ┆          ┆   ┆           ┆ 星打 +1 … ┆           ┆           │
│ …        ┆ …          ┆ …         ┆ …        ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 10008557 ┆ 凤雏庞统宝 ┆           ┆ 10008651 ┆ … ┆ ["力量",  ┆ +75 +75   ┆ ["[should ┆           │
│          ┆ 珠         ┆           ┆          ┆   ┆ "智力", … ┆ +75 +75   ┆ er]"]     ┆           │
│          ┆            ┆           ┆          ┆   ┆ "魔法暴击 ┆ +5% 1-30  ┆           ┆           │
│          ┆            ┆           ┆          ┆   ┆ 率"]      ┆ 主动技能  ┆           ┆           │
│          ┆            ┆           ┆          ┆   ┆           ┆ 等…       ┆           ┆           │
│ 10015655 ┆ 藏有女魔法 ┆           ┆ 10015651 ┆ … ┆ ["技能等  ┆ 20-25 主  ┆ ["[should ┆           │
│          ┆ 师佣兵力量 ┆           ┆          ┆   ┆ 级提升"]  ┆ 动技能等  ┆ er]", "[w ┆           │
│          ┆ 的宝珠     ┆           ┆          ┆   ┆           ┆ 级 +1     ┆ aist]",   ┆           │
│          ┆            ┆           ┆          ┆   ┆           ┆           ┆ "[sh…     ┆           │
│ 10015656 ┆ 藏有格斗家 ┆           ┆ 10015652 ┆ … ┆ ["技能等  ┆ 30-35 主  ┆ ["[should ┆           │
│          ┆ 佣兵力量的 ┆           ┆          ┆   ┆ 级提升"]  ┆ 动技能等  ┆ er]", "[w ┆           │
│          ┆ 宝珠       ┆           ┆          ┆   ┆           ┆ 级 +1     ┆ aist]",   ┆           │
│          ┆            ┆           ┆          ┆   ┆           ┆           ┆ "[sh…     ┆           │
│ 10015657 ┆ 藏有女枪手 ┆           ┆ 10015653 ┆ … ┆ ["技能等  ┆ 40-45 主  ┆ ["[should ┆           │
│          ┆ 佣兵力量的 ┆           ┆          ┆   ┆ 级提升"]  ┆ 动技能等  ┆ er]", "[w ┆           │
│          ┆ 宝珠       ┆           ┆          ┆   ┆           ┆ 级 +1     ┆ aist]",   ┆           │
│          ┆            ┆           ┆          ┆   ┆           ┆           ┆ "[sh…     ┆           │
│ 10015658 ┆ 藏有暗夜使 ┆           ┆ 10015654 ┆ … ┆ ["技能等  ┆ 20-45 主  ┆ ["[should ┆           │
│          ┆ 者佣兵力量 ┆           ┆          ┆   ┆ 级提升"]  ┆ 动技能等  ┆ er]", "[w ┆           │
│          ┆ 的宝珠     ┆           ┆          ┆   ┆           ┆ 级 +1     ┆ aist]",   ┆           │
│          ┆            ┆           ┆          ┆   ┆           ┆           ┆ "[sh…     ┆           │
└──────────┴────────────┴───────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [50]:
df

shape: (261, 12)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ orb_id    ┆ orb_name  ┆ orb_name2 ┆ card_id   ┆ … ┆ enchant_c ┆ effect_di ┆ apply_par ┆ stat_des │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ategory_d ┆ splay     ┆ ts        ┆ c        │
│ i64       ┆ str       ┆ str       ┆ i64       ┆   ┆ isplay    ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ ---       ┆ str       ┆ list[str] ┆ str      │
│           ┆           ┆           ┆           ┆   ┆ list[str] ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2600294   ┆ 光之城主  ┆ Sieghart  ┆ 3600      ┆ … ┆ ["属性攻  ┆ 光        ┆ ["[weapon ┆          │
│           ┆ 赛格哈特  ┆ : Lord of ┆           ┆   ┆ 击"]      ┆           ┆ ]"]       ┆          │
│           ┆ 的宝珠    ┆ Light's   ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Cas…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2600295   ┆ 长脚罗特  ┆ Lotus of  ┆ 3601      ┆ … ┆ ["力量"]  ┆ +26       ┆ ["[weapon ┆          │
│           ┆ 斯的宝珠  ┆ Long Foot ┆           ┆   ┆           ┆           ┆ ]",       ┆          │
│           ┆           ┆ Bead      ┆           ┆   ┆           ┆           ┆ "[coat]", ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ "[pants…  ┆          │
│ 2600296   ┆ 邪龙斯皮  ┆ Head of   ┆ 3602      ┆ … ┆ ["魔法暴  ┆ +3%       ┆ ["[should ┆          │
│           ┆ 兹的宝珠  ┆ Spirrazzi ┆           ┆   ┆ 击率"]    ┆           ┆ er]"]     ┆          │
│           ┆           ┆ : Dead    ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Drago…    ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2600297   ┆ 魔笛使者  ┆ Peter The ┆ 3603      ┆ … ┆ ["智力"]  ┆ +26       ┆ ["[weapon ┆          │
│           ┆ 皮特的宝  ┆ Piper     ┆           ┆   ┆           ┆           ┆ ]",       ┆          │
│           ┆ 珠        ┆ Bead      ┆           ┆   ┆           ┆           ┆ "[coat]", ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ "[pants…  ┆          │
│ 2600298   ┆ 烈焰彼诺  ┆ Vinoshu   ┆ 3604      ┆ … ┆ ["属性攻  ┆ 火        ┆ ["[weapon ┆          │
│           ┆ 修的宝珠  ┆ of Flame  ┆           ┆   ┆ 击"]      ┆           ┆ ]"]       ┆          │
│           ┆           ┆ Bead      ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 690000298 ┆ 勇者的祝  ┆ summer    ┆ 690000299 ┆ … ┆ ["力量",  ┆ +20 +20   ┆ ["[weapon ┆          │
│           ┆ 福        ┆ bead      ┆           ┆   ┆ "智力"]   ┆           ┆ ]", "[wri ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ st]", …   ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ "[ri…     ┆          │
│ 10015655  ┆ 藏有女魔  ┆           ┆ 10015651  ┆ … ┆ ["技能等  ┆ 20-25 主  ┆ ["[should ┆          │
│           ┆ 法师佣兵  ┆           ┆           ┆   ┆ 级提升"]  ┆ 动技能等  ┆ er]", "[w ┆          │
│           ┆ 力量的宝  ┆           ┆           ┆   ┆           ┆ 级 +1     ┆ aist]",   ┆          │
│           ┆ 珠        ┆           ┆           ┆   ┆           ┆           ┆ "[sh…     ┆          │
│ 10015656  ┆ 藏有格斗  ┆           ┆ 10015652  ┆ … ┆ ["技能等  ┆ 30-35 主  ┆ ["[should ┆          │
│           ┆ 家佣兵力  ┆           ┆           ┆   ┆ 级提升"]  ┆ 动技能等  ┆ er]", "[w ┆          │
│           ┆ 量的宝珠  ┆           ┆           ┆   ┆           ┆ 级 +1     ┆ aist]",   ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ "[sh…     ┆          │
│ 10015657  ┆ 藏有女枪  ┆           ┆ 10015653  ┆ … ┆ ["技能等  ┆ 40-45 主  ┆ ["[should ┆          │
│           ┆ 手佣兵力  ┆           ┆           ┆   ┆ 级提升"]  ┆ 动技能等  ┆ er]", "[w ┆          │
│           ┆ 量的宝珠  ┆           ┆           ┆   ┆           ┆ 级 +1     ┆ aist]",   ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ "[sh…     ┆          │
│ 10015658  ┆ 藏有暗夜  ┆           ┆ 10015654  ┆ … ┆ ["技能等  ┆ 20-45 主  ┆ ["[should ┆          │
│           ┆ 使者佣兵  ┆           ┆           ┆   ┆ 级提升"]  ┆ 动技能等  ┆ er]", "[w ┆          │
│           ┆ 力量的宝  ┆           ┆           ┆   ┆           ┆ 级 +1     ┆ aist]",   ┆          │
│           ┆ 珠        ┆           ┆           ┆   ┆           ┆           ┆ "[sh…     ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [51]:
parts = df.select('apply_parts').to_series().to_list()
import itertools

parts = list(set(itertools.chain.from_iterable(parts)))
print(parts)
options = {}
for p in parts:
    category_list = df.filter(pl.col('apply_parts').list.contains(p)).select(
        pl.col('enchant_category_display')).to_series().to_list()
    category_list = list(set(chain.from_iterable(category_list)))
    category_list.sort()
    options[p] = category_list

print(options)

['[title name]', '[unlimited challenge]', '[foil]', '[wrist]', '[waist]', '[pants]', '[support]', '[magic stone]', '[shoulder]', '[coat]', '[weapon]', '[amulet]', '[ring]', '[shoes]']
{'[title name]': ['HP 最大值', 'MP 最大值', '僵直', '力量', '所有属性强化', '技能等级提升', '智力', '物理攻击力', '物理防御', '独立攻击力', '硬直', '魔法攻击力', '魔法防御'], '[unlimited challenge]': ['HP 最大值', 'MP 最大值', '攻击速度', '火属性抗性', '物理暴击率', '硬直', '释放速度', '魔法暴击率'], '[foil]': ['HP 最大值', 'MP 最大值', '力量', '攻击速度', '智力', '火属性抗性', '物理暴击率', '硬直', '移动速度', '释放速度', '魔法暴击率'], '[wrist]': ['HP 回复速度', '僵直', '光属性强化', '光属性抗性', '冰属性强化', '力量', '所有属性强化', '智力', '暗属性强化', '火属性强化', '火属性抗性', '独立攻击力'], '[waist]': ['HP 最大值', 'MP 最大值', '力量', '技能等级提升', '智力', '物理攻击力', '物理暴击率', '物理防御', '独立攻击力', '魔法攻击力', '魔法暴击率', '魔法防御'], '[pants]': ['力量', '所有属性抗性', '攻击速度', '智力', '暗属性抗性', '火属性抗性', '物理攻击力', '物理暴击率', '特殊效果', '独立攻击力', '硬直', '移动速度', '释放速度', '魔法攻击力', '魔法暴击率'], '[support]': ['技能等级提升', '物理攻击力', '特殊效果', '独立攻击力', '释放速度', '魔法攻击力'], '[magic stone]': ['所有属性强化', '物理攻击力', '独立攻击力', '魔法攻击力'], '[shoulder]': ['HP 最大值', 'MP 最大值', '力量', '技能等级提升', '智力', '物理攻击力', '物理暴击率', '物理防御', '独立攻击力', '释放速度', '魔法攻击力', '魔法暴击率', '魔法防御'], '[coat]': ['力量', '攻击速度', '智力', '物理攻击力', '物理暴击率', '独立攻击力', '释放速度', '魔法攻击力', '魔法暴击率'], '[weapon]': ['力量', '命中率', '属性攻击', '攻击速度', '智力', '物理攻击力', '独立攻击力', '释放速度', '魔法攻击力'], '[amulet]': ['僵直', '光属性强化', '冰属性强化', '力量', '所有属性强化', '所有异常状态抗性', '技能等级提升', '智力', '暗属性强化', '束缚抗性', '火属性强化', '火属性抗性', '独立攻击力', '石化抗性'], '[ring]': ['MP 回复速度', '中毒抗性', '僵直', '光属性强化', '冰属性强化', '减速抗性', '力量', '所有属性强化', '智力', '暗属性强化', '火属性强化', '火属性抗性', '独立攻击力'], '[shoes]': ['HP 最大值', 'MP 最大值', '力量', '回避率', '技能等级提升', '智力', '物理攻击力', '物理暴击率', '物理防御', '独立攻击力', '移动速度', '跳跃力', '魔法攻击力', '魔法暴击率', '魔法防御']}